def get_food_data
  food_data = {
    "almonds" => {
                  item_name: "Almonds, Whole",
                  taste: "Salty",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "165",
                },
    "apple" => {
                  item_name: "Apple",
                  taste: "Sweet",
                  texture: "Crunchy",
                  amount: "1 Apple",
                  calories: "80",
                },
    "bananas" => {
                  item_name: "Bananas",
                  taste: "Sweet",
                  texture: "Creamy",
                  amount: "1 Banana",
                  calories: "105",
                },
    "blueberries" => {
                  item_name: "Blueberries, Raw",
                  taste: "Sweet",
                  texture: "Firm",
                  amount: "1 Cup",
                  calories: "80",
                },
    "bb_muffin" => {
                  item_name: "Blueberry Muffin",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "1 Muffin",
                  calories: "140",
                },
    "broccoli" => {
                  item_name: "Broccoli, Raw",
                  taste: "Savory",
                  texture: "Crunchy",
                  amount: "1 Cup",
                  calories: "40",
                },
    "brownie" => {
                  item_name: "Brownie, frosted w/ nuts",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "1 Brownie",
                  calories: "100",
                },
    "cap_n_crnch" => {
                  item_name: "Cap'n Crunch Cereal",
                  taste: "Sweet",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "120",
                },
    "carrots" => {
                  item_name: "Carrots, Raw",
                  taste: "Savory",
                  texture: "Crunchy",
                  amount: "1 Carrot",
                  calories: "30",
                },
    "cashew" => {
                  item_name: "Cashew Nuts, Dry Roastd,Salted",
                  taste: "Salty",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "165",
                },
    "cauliflower" => {
                  item_name: "Cauliflower, Raw",
                  taste: "Savory",
                  texture: "Crunchy",
                  amount: "1 Cup",
                  calories: "25",
                },
    "celery" => {
                  item_name: "Celery, Raw",
                  taste: "Savory",
                  texture: "Crunchy",
                  amount: "1 Stalk",
                  calories: "5",
                },
    "cheddar_cheese" => {
                  item_name: "Cheddar Cheese",
                  taste: "Savory",
                  texture: "Creamy",
                  amount: "1 oz",
                  calories: "115",
                },
    "cheerios" => {
                  item_name: "Cheerios Cereal",
                  taste: "Sweet",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "110",
                },
    "pb_cheese_crackers" => {
                  item_name: "Peanut Butter & Cheese Crackers",
                  taste: "Salty",
                  texture: "Crunchy",
                  amount: "1 Piece",
                  calories: "40",
                },
    "cherry_pie" => {
                  item_name: "Cherry Pie",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "1 Slice",
                  calories: "410",
                },
    "chicken" => {
                  item_name: "Chicken, Roasted, Breast",
                  taste: "Savory",
                  texture: "Firm",
                  amount: "3 oz",
                  calories: "140",
                },
    "choc_chip_cookie" => {
                  item_name: "Chocolate Chip Cookies",
                  taste: "Sweet",
                  texture: "Crunchy",
                  amount: "4 Cookies",
                  calories: "180",
                },
    "fritos" => {
                  item_name: "Fritos",
                  taste: "Salty",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "155",
                },
    "cottage_cheese" => {
                  item_name: "Cottage Cheese, Lowfat 2%",
                  taste: "Savory",
                  texture: "Creamy",
                  amount: "1 Cup",
                  calories: "205",
                },
    "croissant" => {
                  item_name: "Croissant",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "1 Crosst",
                  calories: "235",
                },
    "doughnut" => {
                  item_name: "Doughnut",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "1 Donut",
                  calories: "235",
                },
    "gg_hb" => {
                  item_name: "Egg, Hard-Boiled",
                  taste: "Savory",
                  texture: "Firm",
                  amount: "1 Egg",
                  calories: "75",
                },
    "feta_cheese" => {
                  item_name: "Feta Cheese",
                  taste: "Savory",
                  texture: "Creamy",
                  amount: "1 oz",
                  calories: "75",
                },
    "graham_cracker" => {
                  item_name: "Graham Cracker",
                  taste: "Sweet",
                  texture: "Crunchy",
                  amount: "2 Crackers",
                  calories: "60",
                },
    "grapes" => {
                  item_name: "Grapes, Raw",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "10 Grapes",
                  calories: "35",
                },
    "ice_cream" => {
                  item_name: "Ice Cream, Vanlla, Soft Serve",
                  taste: "Sweet",
                  texture: "Creamy",
                  amount: "1 Cup",
                  calories: "375",
                },
    "kiwifruit" => {
                  item_name: "Kiwifruit, Raw",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "1 Kiwi",
                  calories: "45",
                },
    "lucky_charms" => {
                  item_name: "Lucky Charms Cereal",
                  taste: "Sweet",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "110",
                },
    "mac_nuts" => {
                  item_name: "Macadamia Nuts",
                  taste: "Savory",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "205",
                },
    "marshmallows" => {
                  item_name: "Marshmallows",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "1 oz",
                  calories: "90",
                },
    "mms_plain" => {
                  item_name: "M & Ms, plain",
                  taste: "Sweet",
                  texture: "Creamy",
                  amount: "1 oz",
                  calories: "145",
                },
    "mms_peanut" => {
                  item_name: "M & Ms, peanut",
                  taste: "Sweet",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "155",
                },
    "mix_nuts" => {
                  item_name: "Mixed Nuts",
                  taste: "Salty",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "170",
                },
    "moz_cheese" => {
                  item_name: "Mozzarella Cheese",
                  taste: "Savory",
                  texture: "Creamy",
                  amount: "1 oz",
                  calories: "80",
                },
    "granola" => {
                  item_name: "Granola",
                  taste: "Sweet",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "125",
                },
    "oat_cookies" => {
                  item_name: "Oatmeal w/ Raisins Cookies",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "4 Cookies",
                  calories: "245",
                },
    "oranges" => {
                  item_name: "Oranges, Raw",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "1 Orange",
                  calories: "60",
                },
    "amer_cheese" => {
                  item_name: "American Cheese",
                  taste: "Savory",
                  texture: "Creamy",
                  amount: "1 oz",
                  calories: "105",
                },
    "pb" => {
                  item_name: "Peanut Butter",
                  taste: "Savory",
                  texture: "Creamy",
                  amount: "1 Tbsp",
                  calories: "95",
                },
    "pb_cookie" => {
                  item_name: "Peanut Butter Cookie",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "4 Cookies",
                  calories: "245",
                },
    "pecans" => {
                  item_name: "Pecans, Halves",
                  taste: "Savory",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "190",
                },
    "sweet_pepper" => {
                  item_name: "Peppers, Sweet, Raw, Red",
                  taste: "Savory",
                  texture: "Crunchy",
                  amount: "1 Pepper",
                  calories: "20",
                },
    "dill_pickle" => {
                  item_name: "Pickles, Cucumber, Dill",
                  taste: "Salty",
                  texture: "Crunchy",
                  amount: "1 Pickle",
                  calories: "5",
                },
    "pineapple" => {
                  item_name: "Pineapple, Raw, Diced",
                  taste: "Sweet",
                  texture: "Firm",
                  amount: "1 Cup",
                  calories: "75",
                },
    "pistachio" => {
                  item_name: "Pistachio Nuts",
                  taste: "Savory",
                  texture: "Crunchy",
                  amount: "1 oz",
                  calories: "165",
                },
    "pita" => {
                  item_name: "Pita Bread",
                  taste: "Savory",
                  texture: "Soft",
                  amount: "1 Pita",
                  calories: "165",
                },
    "pizza" => {
                  item_name: "Pizza, Cheese",
                  taste: "Savory",
                  texture: "Chewy",
                  amount: "1 Slice",
                  calories: "290",
                },
    "popcorn" => {
                  item_name: "Popcorn, Popped, Veg Oil,Saltd",
                  taste: "Salty",
                  texture: "Crunchy",
                  amount: "1 Cup",
                  calories: "55",
                },
    "popsicle" => {
                  item_name: "Popsicle",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "1 Popsicle",
                  calories: "70",
                },
    "potato_chips" => {
                  item_name: "Potato Chips",
                  taste: "Salty",
                  texture: "Crispy",
                  amount: "10 Chips",
                  calories: "105",
                },
    "potato_salad" => {
                  item_name: "Potato Salad",
                  taste: "Savory",
                  texture: "Soft",
                  amount: "1 Cup",
                  calories: "360",
                },
    "fries" => {
                  item_name: "French Fries",
                  taste: "Savory",
                  texture: "Crispy",
                  amount: "10 Fries",
                  calories: "160",
                },
    "pretzels" => {
                  item_name: "Pretzels, Twisted, Thin",
                  taste: "Salty",
                  texture: "Crispy",
                  amount: "10 Pretzels",
                  calories: "240",
                },
    "provo_cheese" => {
                  item_name: "Provolone Cheese",
                  taste: "Savory",
                  texture: "Creamy",
                  amount: "1 oz",
                  calories: "100",
                },
    "choc_pudding" => {
                  item_name: "Chocolate Pudding",
                  taste: "Sweet",
                  texture: "Creamy",
                  amount: "5 oz",
                  calories: "205",
                },
    "raisins" => {
                  item_name: "Raisins",
                  taste: "Sweet",
                  texture: "Chewy",
                  amount: "1 Packet",
                  calories: "40",
                },
    "saltines" => {
                  item_name: "Saltines",
                  taste: "Salty",
                  texture: "Crispy",
                  amount: "4 Crackers",
                  calories: "50",
                },
    "sandwhich_cookie" => {
                  item_name: "Sandwich Cookie",
                  taste: "Sweet",
                  texture: "Crunchy",
                  amount: "4 Cookies",
                  calories: "195",
                },
    "chocolate" => {
                  item_name: "Chocolate, semisweet",
                  taste: "Sweet",
                  texture: "Firm",
                  amount: "1 Cup",
                  calories: "860",
                },
    "snack_cake" => {
                  item_name: "Devils Food Snack Cake",
                  taste: "Sweet",
                  texture: "Soft",
                  amount: "1 Sm Cake",
                  calories: "105",
                },
    "strawberries" => {
                  item_name: "Strawberries, Raw",
                  taste: "Sweet",
                  texture: "Firm",
                  amount: "1 Cup",
                  calories: "45",
                },
    "tuna_salad" => {
                  item_name: "Tuna Salad",
                  taste: "Savory",
                  texture: "Creamy",
                  amount: "1 Cup",
                  calories: "375",
                },
    "turkey" => {
                  item_name: "Turkey, Roasted, Light Meat",
                  taste: "Savory",
                  texture: "Firm",
                  amount: "1 oz",
                  calories: "135",
                },
    "walnuts" => {
                  item_name: "Walnuts, English, Pieces",
                  taste: "Savory",
                  texture: "Crunchy",
                  amount: "3 oz",
                  calories: "180",
                },
    "watermelon" => {
                  item_name: "Watermelon, Raw, Diced",
                  taste: "Sweet",
                  texture: "Firm",
                  amount: "1 Cup",
                  calories: "50",
                },
    "wheat_crackers" => {
                  item_name: "Wheat Thin Crackers",
                  taste: "Savory",
                  texture: "Crispy",
                  amount: "4 Crackers",
                  calories: "35",
                },
    "yogurt" => {
                  item_name: "Yogurt",
                  taste: "Savory",
                  texture: "Creamy",
                  amount: "8 oz",
                  calories: "145",
                }
    }
  return food_data
end
